server:
  port: 3080
spring:
  application:
    name: minio-upload-api
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/minio-upload?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: kjj0427

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  typeAliasesPackage: xyz.huanggy.*.entity
  global-config:
    id-type: 2
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
      logic-delete-field: deleted
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

logging:
  level:
    xyz.huanggy.*.mapper: debug



